AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for ML Project FastAPI (Loan Prediction)

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  LoanApplicationApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HttpApi:
          Type: HttpApi
    Metadata:
      Dockerfile: Dockerfile.lambda
      DockerContext: .
      DockerTag: v1

  LoanApplicationUiBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  LoanApplicationUiBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LoanApplicationUiBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${LoanApplicationUiBucket.Arn}/*"

Outputs:
  BackendApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"

  FrontendWebsiteUrl:
    Description: "URL for the hosted frontend"
    Value: !GetAtt LoanApplicationUiBucket.WebsiteURL
