FROM public.ecr.aws/lambda/python:3.11

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy the rest of the application code
COPY . ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler
CMD [ "src.app.main.handler" ]
