name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this to your preferred region

      - name: SAM Build
        run: sam build --use-container

      - name: SAM Deploy
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
            --stack-name loan-prediction-stack \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --resolve-image-repos

      - name: Get Stack Outputs
        id: outputs
        run: |
          BACKEND_URL=$(aws cloudformation describe-stacks --stack-name loan-prediction-stack --query "Stacks[0].Outputs[?OutputKey=='BackendApiUrl'].OutputValue" --output text)
          BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name loan-prediction-stack --query "Stacks[0].Outputs[?OutputKey=='LoanApplicationUiBucket'].OutputValue" --output text)
          FRONTEND_URL=$(aws cloudformation describe-stacks --stack-name loan-prediction-stack --query "Stacks[0].Outputs[?OutputKey=='FrontendWebsiteUrl'].OutputValue" --output text)
          
          echo "--------------------------------------------------"
          echo "DEPLOYMENT SUCCESSFUL!"
          echo "Backend API URL: $BACKEND_URL"
          echo "Frontend S3 Bucket: $BUCKET_NAME"
          echo "Frontend Website URL: $FRONTEND_URL"
          echo "--------------------------------------------------"
          
          echo "backend_url=$BACKEND_URL" >> $GITHUB_OUTPUT
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT

      - name: Sync UI to S3
        run: |
          # Inject the backend URL into main.js
          sed -i "s|const DEPLOYED_URL = '';|const DEPLOYED_URL = '${{ steps.outputs.outputs.backend_url }}';|g" ./loan-app-ui/main.js
          aws s3 sync ./loan-app-ui s3://${{ steps.outputs.outputs.bucket_name }} --delete
